// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserService.proto

package Services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegReponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegReponse) Reset()         { *m = RegReponse{} }
func (m *RegReponse) String() string { return proto.CompactTextString(m) }
func (*RegReponse) ProtoMessage()    {}
func (*RegReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{0}
}

func (m *RegReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegReponse.Unmarshal(m, b)
}
func (m *RegReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegReponse.Marshal(b, m, deterministic)
}
func (m *RegReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegReponse.Merge(m, src)
}
func (m *RegReponse) XXX_Size() int {
	return xxx_messageInfo_RegReponse.Size(m)
}
func (m *RegReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegReponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegReponse proto.InternalMessageInfo

func (m *RegReponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegReponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegReponse)(nil), "Services.RegReponse")
}

func init() {
	proto.RegisterFile("UserService.proto", fileDescriptor_e7864342a5dd7108)
}

var fileDescriptor_e7864342a5dd7108 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x2d, 0x4e, 0x2d,
	0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80,
	0x72, 0x8b, 0xa5, 0xb8, 0x40, 0x92, 0x10, 0x51, 0x25, 0x3b, 0x2e, 0xae, 0xa0, 0xd4, 0xf4, 0xa0,
	0xd4, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8,
	0x38, 0x31, 0x3d, 0x55, 0x82, 0x09, 0x2c, 0x01, 0xe3, 0x1a, 0x39, 0x73, 0x71, 0x23, 0x59, 0x25,
	0x64, 0xc2, 0xc5, 0x0e, 0xe2, 0x06, 0xa5, 0xa6, 0x0b, 0x09, 0xeb, 0xc1, 0x2c, 0xd4, 0x03, 0x09,
	0xf9, 0xe6, 0xa7, 0xa4, 0xe6, 0x48, 0x89, 0x20, 0x04, 0x11, 0xd6, 0x26, 0xb1, 0x81, 0xdd, 0x62,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x48, 0xd0, 0x84, 0xf8, 0xb6, 0x00, 0x00, 0x00,
}
